# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            orrecled
tagline:          'A place to develope my thinking and career'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/orrecled" target="_blank">@orrecled</a>.'
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/orrecled

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
