# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            orrecled
tagline:          'Thinking space'
description:      'A place to develope my thinking and career.Also en español. Made by <a href="https://twitter.com/orrecled" target="_blank">@orrecled</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Orrecled'
  url:            https://twitter.com/orrecled

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
